name: pytorch_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scikit-learn
  - numpy
  - scipy
  - pyarrow
  - ipykernel
  - Jupyter
  - networkx
  - matplotlib
  - geopandas
  - shapely
  - regex
  - lxml
  - tqdm
  - tensorboard
  - lightning
  - pip
  - optuna
  - pip:
    - pandas[performance]
    - meteostat
    - torch
    - torchvision
    - torchaudio
    - torch-tb-profiler
    - torchmetrics
